--UC1:
CREATE DATABASE ADDRESSBOOK_SERVICE
SELECT * FROM SYS.DATABASES
USE ADDRESSBOOK_SERVICE

--UC2:
CREATE TABLE ADDRESS_BOOK(
ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE FLOAT NOT NULL,
PHONE_NUMBER FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL)

SELECT * FROM ADDRESS_BOOK


--UC3:
INSERT INTO ADDRESS_BOOK VALUES('Harini','Lekkala','11A','Vizag','Visakhapatnam',654321,9087654321,'harini.lekkala1997@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Harshini','Potnuri','12B','Madhurwada','Vsp',645321,8907654321,'harshini.potnuri1997@gmail.com')
INSERT INTO ADDRESS_BOOK VALUES('Pardhavi','Neeli','13C','Rajasthan','Jaipur',634521,7890123456,'pardhavi.neeli@gmail.com')



--UC4:
UPDATE ADDRESS_BOOK SET CITY = 'Podugupalem' WHERE FIRST_NAME = 'Harini'

--UC5:
DELETE FROM ADDRESS_BOOK WHERE FIRST_NAME = 'Pardhavi'

--UC6:
SELECT * FROM ADDRESS_BOOK WHERE CITY = 'Podugupalem'
SELECT * FROM ADDRESS_BOOK WHERE STATE = 'Vsp'

--UC7:
SELECT CITY, COUNT(CITY) AS CITY_COUNT FROM ADDRESS_BOOK GROUP BY CITY
SELECT STATE, COUNT(STATE) AS STATE_COUNT FROM ADDRESS_BOOK GROUP BY STATE

--UC8:
SELECT * FROM ADDRESS_BOOK WHERE CITY = 'Podugupalem' ORDER BY FIRST_NAME ASC

--UC9:
ALTER TABLE ADDRESS_BOOK ADD TYPE VARCHAR(20) NOT NULL DEFAULT('')
UPDATE ADDRESS_BOOK SET TYPE = 'Family' WHERE FIRST_NAME = 'Harini'
UPDATE ADDRESS_BOOK SET TYPE = 'Family' WHERE FIRST_NAME = 'Harshini'
--UPDATE ADDRESS_BOOK SET TYPE = 'Family' WHERE FIRST_NAME = 'Pardhavi'

--UC10:
SELECT TYPE, COUNT(TYPE) AS TYPE_COUNT FROM ADDRESS_BOOK GROUP BY TYPE

--UC11:
INSERT INTO ADDRESS_BOOK VALUES('vennila','Raj','20Z','Madhurwada','Tamil Nadu',612345,6543217890,'anand@gmail.com','Friends')
INSERT INTO ADDRESS_BOOK VALUES('ojaswi','Raj','20Z','Visakhapatnam','Podugupalem',612345,6543217890,'anand@gmail.com','Family')

SELECT * FROM ADDRESS_BOOK

DELETE FROM ADDRESS_BOOK WHERE ID = '7'

SELECT * FROM ADDRESS_BOOK

--UC12:
--CREATING CONTACT_TYPE TABLE
CREATE TABLE CONTACT_TYPE(
TYPE_ID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
TYPE_NAME VARCHAR(25) NOT NULL)

INSERT INTO CONTACT_TYPE VALUES('Family'),('Friends'),('Colleagues')

SELECT * FROM CONTACT_TYPE

--CREATING CONTACT_ADDRESS TABLE
CREATE TABLE CONTACT_ADDRESS(
CONTACT_ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
FIRST_NAME VARCHAR(25) NOT NULL,
LAST_NAME VARCHAR(25) NOT NULL,
ADDRESS VARCHAR(100) NOT NULL,
CITY VARCHAR(25) NOT NULL,
STATE VARCHAR(25) NOT NULL,
ZIP_CODE FLOAT NOT NULL,
EMAIL VARCHAR(50) NOT NULL,
TYPE_ID INT NOT NULL)

SELECT * FROM CONTACT_ADDRESS

INSERT INTO CONTACT_ADDRESS VALUES('Harini','Lekkala','11A','Salem','Tamil Nadu',654321,'harini@gmail.com',1)
INSERT INTO CONTACT_ADDRESS VALUES('Harshini','Potnuri','12B','Coimbatore','Tamil Nadu',645321,'harshini@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('swathi','Kumar','13C','Dindigul','Tamil Nadu',634521,'swathi@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('sunitha','Selvan','14D','Tirupur','Tamil Nadu',621345,'sunitha@gmail.com',2)
INSERT INTO CONTACT_ADDRESS VALUES('Steven','John','15E','Chennai','Tamil Nadu',456321,'steven@gmail.com',3)
INSERT INTO CONTACT_ADDRESS VALUES('ojaswi','Muniyapagounder','11A','Komarapalayam','Tamil Nadu',654321,'ojaswi@gmail.com',1)
INSERT INTO CONTACT_ADDRESS VALUES('Sudha','Shanmugam','16F','Coimbatore','Tamil Nadu',645312,'sudha@gmail.com',1)
INSERT INTO CONTACT_ADDRESS VALUES('sravani','lekkala','11A','Komarapalayam','Tamil Nadu',456321,'sravani@gmail.com',1)

--CREATING CONTACT_PHONE TABLE
CREATE TABLE CONTACT_PHONE(
CONTACT_ID INT NOT NULL,
FIRST_NAME VARCHAR(25) NOT NULL,
PHONE_1 FLOAT NOT NULL,
PHONE_2 FLOAT NULL)

INSERT INTO CONTACT_PHONE VALUES(1,'Harini',9087654321,6987523410)
INSERT INTO CONTACT_PHONE (CONTACT_ID,FIRST_NAME,PHONE_1) VALUES(2,'Lekkala',8907654321)
INSERT INTO CONTACT_PHONE VALUES(3,'sunitha',7890123456,7689054321)
INSERT INTO CONTACT_PHONE VALUES(4,'sravani',6543217890,8906745123)
INSERT INTO CONTACT_PHONE VALUES(5,'Steven',9907564231,7908645231)
INSERT INTO CONTACT_PHONE (CONTACT_ID,FIRST_NAME,PHONE_1) VALUES(6,'Appusamy',6789054123)
INSERT INTO CONTACT_PHONE VALUES(7,'Sudha',7890654321,6795321405)
INSERT INTO CONTACT_PHONE VALUES(8,'sravani',9786672345,8755428901)

SELECT * FROM CONTACT_PHONE

--ADDING CONSTRAINTS TO THE TABLE
ALTER TABLE CONTACT_ADDRESS ADD CONSTRAINT FK_CONTACT_TYPE FOREIGN KEY(TYPE_ID) REFERENCES CONTACT_TYPE(TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
ALTER TABLE CONTACT_PHONE ADD CONSTRAINT FK_CONTACT_PHONE FOREIGN KEY(CONTACT_ID) REFERENCES CONTACT_ADDRESS(CONTACT_ID) ON DELETE CASCADE ON UPDATE CASCADE

--UC13:Ensuring UC6, UC7, UC8, UC10
SELECT * FROM CONTACT_ADDRESS WHERE CITY = 'Komarapalayam'
SELECT * FROM CONTACT_ADDRESS WHERE STATE = 'Tamil Nadu'

SELECT CITY, COUNT(CITY) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY CITY
SELECT STATE, COUNT(STATE) AS CONTACT_ADDRESS FROM ADDRESS_BOOK GROUP BY STATE

SELECT * FROM CONTACT_ADDRESS WHERE CITY = 'Komarapalayam' ORDER BY FIRST_NAME ASC

SELECT TYPE_NAME,COUNT(TYPE_NAME) AS COUNT FROM CONTACT_TYPE CT INNER JOIN CONTACT_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID GROUP BY TYPE_NAME
SELECT TYPE_NAME,CA.FIRST_NAME,PHONE_1 FROM CONTACT_TYPE CT INNER JOIN CONTACT_ADDRESS CA ON CT.TYPE_ID = CA.TYPE_ID 
INNER JOIN CONTACT_PHONE CP ON CA.CONTACT_ID = CP.CONTACT_ID

--PROCEDURE FOR ADDING CONTACTS IN ADDRESS_BOOK TABLE
GO
CREATE OR ALTER PROCEDURE [dbo].[AddContacts]
(@FIRST_NAME VARCHAR(25),
@LAST_NAME VARCHAR(25),
@ADDRESS VARCHAR(100),
@CITY VARCHAR(25),
@STATE VARCHAR(25),
@ZIP_CODE FLOAT,
@PHONE_NUMBER FLOAT,
@EMAIL VARCHAR(50),
@TYPE VARCHAR(20))
AS
BEGIN
INSERT INTO ADDRESS_BOOK VALUES(@FIRST_NAME,@LAST_NAME,@ADDRESS,@CITY,@STATE,@ZIP_CODE,@PHONE_NUMBER,@EMAIL,@TYPE)
END




